services:
  includingtip:
    image: includingtip
    build:
      context: .
      dockerfile: IncludingTip/IncludingTip/Dockerfile
    environment:
      DB_HOST: postgres

  includingtip.client:
    image: includingtip.client
    build:
      context: .
      dockerfile: IncludingTip/IncludingTip.Client/Dockerfile
  
  postgres:
    image: postgres:alpine
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: toor
  
  
  memstore:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    # For better performance, consider `host` mode instead `port` to avoid docker NAT.
    # `host` mode is NOT currently supported in Swarm Mode.
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode
    # network_mode: "host"
    volumes:
      - dragonflydata:/data

volumes:
  postgres_data:
  dragonflydata: